### ISSUE TITLE
Element not copied properly when no "." after listName[ ]

### ISSUE THREAD

**Issue by nayef** [ikelin/jquery.dynamiclist#1]
the element wont be copied properly in the following situation. suppose a `AutoPopulatingList<String> stringValueList` is put into model and used like this,

`<input id="stringValueList0" name="stringValueList[0]" class="list_element" type="text" value=""/>`

When new element is added. the number inside [ ] is not increased. I guess it is because how "." is used in the code `attr = attr.replace(/\d+\./, itemNum + ".");
                        attr = attr.replace(/\[\d+\]\./, "[" + itemNum + "].");`

**Comment by nayef** [comment]
JSTL snippet

`<c:forEach items="${customList.values}" var="item" varStatus="status">`
`<div class="list-item">`
`<form:input path="values[${status.index}]" cssClass="list_element"/>`
`<a class="list-remove btn btn-small"><i class="icon-minus"></i> Remove</a>`
`</div>`
`</c:forEach>`

For the following structure,
`public class CustomList implements Serializable{`
    `private int id;`
    `private AutoPopulatingList<String> values;`
    `//other fields and getter setters`
`}`

**Comment by ikelin** [comment]
The check for `.` is necessary so it doesn't replace digits in other parts of the variable.  This logic, unfortunately, does not bode well when the list is not an object as you have observed.

One work around is to tweak the `attr.replace` logic to not look for a `.`, that'll work for you as long as you do not have any digits in your variable name.  Another work around, albeit hack-ish, is to wrap your `String` in a POJO.
